name: minha_saude
description: "Um aplicativo de saúde conectado ao Supabase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Backend
  supabase_flutter: ^2.3.0
  
  # UI/UX
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  go_router: ^13.0.0
  provider: ^6.1.1
  intl: ^0.20.2
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  # intl: ^0.19.0 # Útil para formatação de datas/moedas

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Configuração de assets (imagens/svgs)
  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
